import { VerticalBox } from "std-widgets.slint";

export component MySlider inherits Rectangle {
    in-out property <float> maximum: 100;
    in-out property <float> minimum: 0;
    in-out property <float> value: 10;

    width: 25px;
    horizontal-stretch: 1;
    vertical-stretch: 0;
    border-radius: root.height / 2;
    clip: true;
    background: touch.pressed ? #eee : #ddd;
    border-width: 1px;
    border-color: root.background.darker(25%);

    handle := Rectangle {
        y: 0px;
        // y: (root.height) * (root.value - root.minimum) / (root.maximum - root.minimum);
        width: parent.width;
        // height: self.width;
        height: (root.height) * (root.value - root.minimum) / (root.maximum - root.minimum);
        border-width: 3px;
        border-radius: self.height / 2;
        background: touch.pressed ? #f8f : touch.has-hover ? #66f : #0000ff;
        border-color: self.background.darker(15%);
        // y: (root.height - handle.height) * (root.value - root.minimum) / (root.maximum - root.minimum);
    }

    touch := TouchArea {
        property <float> pressed-value;
        pointer-event(event) => {
            if (event.button == PointerEventButton.left && event.kind == PointerEventKind.down) {
                self.pressed-value = root.value;
                root.value = touch.pressed-y * (root.maximum - root.minimum) / (root.height - handle.width);
            }
        }
        moved => {
            if (self.enabled && self.pressed) {
                root.value = max(root.minimum, min(root.maximum,
                    self.pressed-value + (touch.mouse-y - touch.pressed-y) * (root.maximum - root.minimum) / (root.height - handle.width)));
            }
        }
    }
}

export component Recipe inherits Window {
    VerticalBox {
        alignment: start;
        slider := MySlider {
            maximum: 100;
        }

        Text {
            text: "Value: \{round(slider.value)}";
        }
    }
}

export component VolumeOSD inherits Window {
    background: pink;
    width: 70px;
    height: 210px;
    Rectangle {
        x: 0px;
        border-radius: 10px;
        width: 45px;
        height: 200px;
        background: black;
        MySlider {
            height: parent.height - 15px;
        }
    }
}
