import { MySlider } from "slider.slint";
export struct osdState {
    is-open:bool,
    restart: bool,
}

export component VolumeOSD inherits Window {
    in-out property <osdState> state: { is-open: false, restart: false };
    in-out property <float> value;
    in-out property <bool> is_muted;
    pure callback get_vol_value();
    pure callback vol_changed(float);
    pure callback call_close();
    pure callback toggle_mute();
    background: transparent;
    width: 80px;
    height: 250px;

    Timer {
        running: true;
        interval: 200ms;
        triggered => {
            if state.restart {
                state.restart = false;
                long_timer.restart();
            }
        }
    }

    Timer {
        running: root.state.is-open;
        interval: 100ms;
        triggered() => {
            root.get_vol_value();
        }
    }

    long_timer := Timer {
        running: root.state.is-open;
        interval: 2s;
        triggered => {
            state.is-open = false;
            call_close();
        }
    }

    Rectangle {
        width: 35px;
        height: 250px;
        border-radius: root.width / 2;
        border-width: 2px;
        x: state.is-open ? 0px : 90px;
        border-color: #B4B4B4;
        background: #000000;
        animate x { duration: 200ms; }
        MySlider {
            y: 5px;
            x: 5px;
            value: root.value;
            set-vol(val) => {
                root.vol_changed(val);
            }
            reset => {
                if state.is_open {
                    state.restart = true;
                }
            }
        }

        Rectangle {
            y: 225px;
            width: 18px;
            height: 18px;
            Image {
                width: parent.width;
                height: parent.height;
                source: is_muted ? @image-url("../assets/mute-volume.svg") : @image-url("../assets/volume-full.svg");
                colorize: #B4B4B4;
            }

            handle := TouchArea {
                clicked => {
                    if is_muted {
                        is_muted = false;
                    } else {
                        is_muted = true;
                    }
                    toggle_mute();
                }
            }
        }
    }
}
