
export component MySlider inherits Rectangle {
    in-out property <float> maximum: 100;
    in-out property <float> minimum: 0;
    in-out property <float> value;
    callback set-vol(float);

    width: 25px;
    height: 215px;
    horizontal-stretch: 1;
    vertical-stretch: 0;
    border-radius: root.width / 2;
    clip: true;

    background: touch.pressed ? #f8f : touch.has-hover ? #66f : #0000ff;
    border-width: 1px;
    border-color: root.background.darker(25%);
    animate background { duration: 200ms; }

    handle := Rectangle {
        y: 0px;
        width: parent.width;
        height: (root.height) * ((root.maximum - root.value) - root.minimum) / (root.maximum - root.minimum);
        border-top-left-radius: self.height / 2;
        border-top-right-radius: self.height / 2;
        background: touch.pressed ? #eee : #ddd;
        animate background { duration: 200ms; }
        animate height {
            delay: 100ms;
            duration: 200ms;
        }
    }

    touch := TouchArea {
        property <float> pressed-value;
        pointer-event(event) => {
            if (event.button == PointerEventButton.left && event.kind == PointerEventKind.down) {
                self.pressed-value = root.value;
                root.value = root.maximum - (touch.pressed-y * (root.maximum - root.minimum) / (root.height - handle.width));
                set_vol(root.value);
            }
        }
        moved => {
            if (self.enabled && self.pressed) {
                root.value = root.maximum - (max(root.minimum, min(root.maximum,
                    self.pressed-value + (touch.mouse-y - touch.pressed-y) * (root.maximum - root.minimum) / (root.height - handle.width))));
                set_vol(root.value);
            }
        }
    }
}
